### ISSUE TITLE
Cluster: The SendConfigurationApply function did not succeed.

### ISSUE THREAD

**Issue by DatabaseDylan** [dsccommunity/FailoverClusterDsc#282]
### Problem description

When utilizing the Cluster resource within FailoverClusteringDsc against a remote and or local target machine, my tests return false, but the SET operation is not executing. I know it is not a permissions issue because I can create the cluster via the GUI without any issues whatsoever using the same credentials I am passing in here.

### Verbose logs

```text
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManag
er,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer myTargetMachine with user sid S-1-5-21-4043616619-4214276085-4066818963-84704.
VERBOSE: [myTargetMachine]: LCM:  [ Start  Set      ]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Resource ]  [[WindowsFeature]AddFailoverFeature]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Test     ]  [[WindowsFeature]AddFailoverFeature]
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddFailoverFeature] The operation 'Get-WindowsFeature' started: Failover-clustering
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddFailoverFeature] The operation 'Get-WindowsFeature' succeeded: Failover-Clustering
VERBOSE: [myTargetMachine]: LCM:  [ End    Test     ]  [[WindowsFeature]AddFailoverFeature]  in 0.7320 seconds.
VERBOSE: [myTargetMachine]: LCM:  [ Skip   Set      ]  [[WindowsFeature]AddFailoverFeature]
VERBOSE: [myTargetMachine]: LCM:  [ End    Resource ]  [[WindowsFeature]AddFailoverFeature]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Resource ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Test     ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature]
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature] The operation 'Get-Wind
owsFeature' started: RSAT-Clustering-PowerShell
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature] The operation 'Get-Wind
owsFeature' succeeded: RSAT-Clustering-PowerShell
VERBOSE: [myTargetMachine]: LCM:  [ End    Test     ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature]  in 0.2270 seconds.
VERBOSE: [myTargetMachine]: LCM:  [ Skip   Set      ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature]
VERBOSE: [myTargetMachine]: LCM:  [ End    Resource ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringPowerShellFeature]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Resource ]  [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Test     ]  [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools]
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools] The operation 'Get-WindowsF
eature' started: RSAT-Clustering-Mgmt
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools] The operation 'Get-WindowsF
eature' succeeded: RSAT-Clustering-Mgmt
VERBOSE: [myTargetMachine]: LCM:  [ End    Test     ]  [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools]  in 0.2270 seconds.
VERBOSE: [myTargetMachine]: LCM:  [ Skip   Set      ]  [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools]
VERBOSE: [myTargetMachine]: LCM:  [ End    Resource ]  [[WindowsFeature]AddRemoteServerAdministrationToolsFailoverManagementTools]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Resource ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Test     ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature]
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature] The operation 'Get-Wi
ndowsFeature' started: RSAT-Clustering-CmdInterface
VERBOSE: [myTargetMachine]:                            [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature] The operation 'Get-Wi
ndowsFeature' succeeded: RSAT-Clustering-CmdInterface
VERBOSE: [myTargetMachine]: LCM:  [ End    Test     ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature]  in 0.2230 seconds.
VERBOSE: [myTargetMachine]: LCM:  [ Skip   Set      ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature]
VERBOSE: [myTargetMachine]: LCM:  [ End    Resource ]  [[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Resource ]  [[Cluster]CreateCluster]
VERBOSE: [myTargetMachine]: LCM:  [ Start  Test     ]  [[Cluster]CreateCluster]
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Checking if cluster myClusterNameObject is present.
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Perform operation 'Enumerate CimInstances' with following parameters, ''namesp
aceName' = root\cimv2,'className' = Win32_ComputerSystem'.
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Operation 'Enumerate CimInstances' complete.
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Enumerating clusters in domain myDomain.com.
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Cluster myClusterNameObject is present.
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Checking if the node myTargetMachine is a member of the cluster myClusterNameObject,
 and so that node status is 'Up'.
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster]    at MS.Internal.ServerClusters.NativeMethods.OpenCluster(String clusterName,
 ClusterAccessRights desiredAccess, ClusterAccessRights& grantedAccess)
   at MS.Internal.ServerClusters.Cluster.Open(String clusterName, ClusterAccessRights desiredAccess)
   at Microsoft.FailoverClusters.PowerShell.ClusterBridge.Open(String name, ClusterAccessRights desiredAccess)
   at Microsoft.FailoverClusters.PowerShell.ClusterPipeCmdlet.get_Clus()
   at Microsoft.FailoverClusters.PowerShell.GetNodeCommand.WrappedProcessRecord()
   at Microsoft.FailoverClusters.PowerShell.FCCmdlet.ProcessRecord()
An error occurred opening cluster 'myClusterNameObject'.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Get-ClusterNode,Microsoft.FailoverClusters.PowerShell.GetNodeCommand
    + PSComputerName        : myTargetMachine.myDomain.com
 
VERBOSE: [myTargetMachine]:                            [[Cluster]CreateCluster] Cluster node myTargetMachine is NOT a member of cluster myClusterNameObject.
VERBOSE: [myTargetMachine]: LCM:  [ End    Test     ]  [[Cluster]CreateCluster]  in 30.7870 seconds.
The PowerShell DSC resource '[Cluster]CreateCluster' with SourceInfo '::88::21::Cluster' threw one or more non-terminating errors while running the 
Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more 
details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : myTargetMachine.myDomain.com
 
VERBOSE: [myTargetMachine]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : myTargetMachine.myDomain.com
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 59.676 seconds
```
```


### DSC configuration

```powershell
@{
    AllNodes = @(
        @{
            NodeName = '*'
           ClusterName = 'myClusterNameObject'
           ClusterIPAddress = @('myIPSubnet1/24','myIPSubnet2/24')
          PSDscAllowDomainUser = $true
         PSDscAllowPlainTextPassword = $true
@}
@)
@}
```
```
if ($Node.SqlAGRole -eq 'PrimaryReplica')
        {
            $i = 0
            foreach ($ipAddress in $Node.ClusterIPAddress){
                $i += 1
                if($i -eq 1){
                    Cluster "CreateCluster"
                    {
                        Name                          = $Node.ClusterName
                        StaticIPAddress               = $ipAddress
                        DependsOn                     = '[WindowsFeature]AddRemoteServerAdministrationToolsClusteringCmdInterfaceFeature'
                        #PsDscRunAsCredential = $CredSSP_domain
                        KeepDownedNodesInCluster = $true
                        DomainAdministratorCredential = $CredSSP
                    }
                } else {
                    ClusterIPAddress "AddClusterIPAddress$i"
                    {
                        IPAddress                     = $ipAddress
                        Ensure                        = 'Present'
                        AddressMask                   =  '255.255.255.0'
                        DependsOn                     = '[Cluster]CreateCluster'
                    }
                }
           
```
```


### Suggested solution

The error is generic, which makes it difficult to pinpoint where it is failing.

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2022 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value                                                                                                                        
----                           -----                                                                                                                        
PSVersion                      5.1.20348.2652                                                                                                               
PSEdition                      Desktop                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                      
BuildVersion                   10.0.20348.2652                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                              
WSManStackVersion              3.0                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                          
SerializationVersion           1.1.0.1
```

### FailoverClusterDsc version

```text
Name               Version Path                                                                                       
----               ------- ----                                                                                       
FailoverClusterDsc 2.1.0   C:\Program Files\WindowsPowerShell\Modules\FailoverClusterDsc\2.1.0\FailoverClusterDsc.psd1
```

**Comment by johlju** [comment]
Reopening and labeled as bug. Community hopefully can resolve this.
